name: Ensure branch is up-to-date

on:
  pull_request:
    branches:
      - main

jobs:
  check-up-to-date:
    name: Ensure branch is up-to-date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Fetch all branches
        run: git fetch --all
      
      - name: Check if branch is behind main
        run: |
          git checkout main
          git pull origin main
          git checkout ${{ github.head_ref }}
          if [ $(git merge-base main ${{ github.head_ref }}) != $(git rev-parse main) ]; then
            echo "Error: Branch is not up-to-date with main."
            exit 1
          fi
